name: devio
description: AI-driven guidance for app development.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.1+4

environment:
  sdk: '>=3.0.0 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  go_router: ^14.8.0
  flutter_bloc: ^9.0.0
  freezed_annotation: ^3.0.0
  json_annotation: ^4.8.1
  intl: ^0.20.2
  uuid: ^4.2.1
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.1.4
  font_awesome_flutter: ^10.7.0
  provider: ^6.1.1
  http: ^1.3.0
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.4
  animate_do: ^4.2.0
  flutter_animate: ^4.5.0
  
  # Webview
  webview_flutter: ^4.7.0
  webview_flutter_wkwebview: ^3.12.0
  
  # Firebase
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  firebase_storage: ^12.4.4
  firebase_analytics: ^11.4.4
  firebase_messaging: ^15.2.4
  firebase_crashlytics: ^4.3.4
  cached_network_image: ^3.3.1
  google_generative_ai: ^0.4.6
  flutter_dotenv: ^5.1.0
  image_picker: ^1.0.7

  # Document handling
  syncfusion_flutter_pdf: ^28.2.9  # For PDF handling
  path: ^1.8.3
  mime: ^2.0.0  # For MIME type detection

  # New dependencies
  google_fonts: ^6.2.1
  smooth_page_indicator: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0
  build_runner: ^2.4.7
  freezed: ^3.0.3
  json_serializable: ^6.7.1
  flutter_launcher_icons: ^0.13.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # Platform-specific configurations


  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/drawer_bg.jpg
    - assets/icons/
    - assets/fonts/
    - .env

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  fonts:
    - family: JosefinSans
      fonts:
        - asset: assets/fonts/JosefinSans-Thin.ttf
          weight: 100
        - asset: assets/fonts/JosefinSans-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/JosefinSans-Light.ttf
          weight: 300
        - asset: assets/fonts/JosefinSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/JosefinSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/JosefinSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/JosefinSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/JosefinSans-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/JosefinSans-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/JosefinSans-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/JosefinSans-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/JosefinSans-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/JosefinSans-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/JosefinSans-BoldItalic.ttf
          weight: 700
          style: italic
