// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQiq1RfFo1Wj3-4gQuRTvdf-BYAc8JZz4',
    appId: '1:575951766528:android:8bb36eefa4ef2be88f44e5',
    messagingSenderId: '575951766528',
    projectId: 'devio-cc71f',
    storageBucket: 'devio-cc71f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGrLf7g9z01GKKeJeSTr9nOX8msS79tII',
    appId: '1:575951766528:ios:efd10c30bbf2e2b78f44e5',
    messagingSenderId: '575951766528',
    projectId: 'devio-cc71f',
    storageBucket: 'devio-cc71f.firebasestorage.app',
    androidClientId:
        '575951766528-lg18aj9d77ah09vr0ftd1tjjgkmip1s8.apps.googleusercontent.com',
    iosClientId:
        '575951766528-kisqr9pk6ki6lhce91n3rdgookec850f.apps.googleusercontent.com',
    iosBundleId: 'dev.artan.devio',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8tfDiosUmyYOEJNy59jXnwO8ryAtXZaE',
    appId: '1:575951766528:web:c66a3d01fead253a8f44e5',
    messagingSenderId: '575951766528',
    projectId: 'devio-cc71f',
    authDomain: 'devio-cc71f.firebaseapp.com',
    storageBucket: 'devio-cc71f.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGrLf7g9z01GKKeJeSTr9nOX8msS79tII',
    appId: '1:575951766528:ios:efd10c30bbf2e2b78f44e5',
    messagingSenderId: '575951766528',
    projectId: 'devio-cc71f',
    storageBucket: 'devio-cc71f.firebasestorage.app',
    androidClientId:
        '575951766528-lg18aj9d77ah09vr0ftd1tjjgkmip1s8.apps.googleusercontent.com',
    iosClientId:
        '575951766528-kisqr9pk6ki6lhce91n3rdgookec850f.apps.googleusercontent.com',
    iosBundleId: 'dev.artan.devio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8tfDiosUmyYOEJNy59jXnwO8ryAtXZaE',
    appId: '1:575951766528:web:fdd4ef0ae67baa5c8f44e5',
    messagingSenderId: '575951766528',
    projectId: 'devio-cc71f',
    authDomain: 'devio-cc71f.firebaseapp.com',
    storageBucket: 'devio-cc71f.firebasestorage.app',
  );
}
